[package]
name = "falcon_account"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.15.1"
falcon = { path = "../falcon" }
openzeppelin_interfaces = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v4.0.0-alpha.0" }
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v4.0.0-alpha.0" }
openzeppelin_utils = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v4.0.0-alpha.0" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.55.0" }
assert_macros = "2.15.1"

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false

[target-defaults.test]
build-external-contracts = [
    "falcon_account::preset::FalconAccount",
]
