[package]
name = "falcon_old"
version = "0.1.0"
edition = "2024_07"

[lib]

[dependencies]

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.55.0" }
assert_macros = "2.15.1"
