[package]
name = "falcon"
version = "0.1.0"
edition = "2024_07"

[lib]

[dependencies]
corelib_imports = "0.1.2"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.55.0" }
assert_macros = "2.15.1"
falcon_zknox = { path = "../falcon_zknox" }
