[package]
name = "falcon"
version = "0.1.0"
edition = "2024_07"

[lib]

[[target.executable]]
name = "main"
function = "falcon::main"
sierra = true

[[target.executable]]
name = "bench_ntt_recursive"
function = "falcon::programs::bench_ntt_recursive::main"
sierra = true

[[target.executable]]
name = "bench_ntt_bounded_int"
function = "falcon::programs::bench_ntt_bounded_int::main"
sierra = true

[dependencies]
cairo_execute = "2.15.1"
corelib_imports = "0.1.2"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.55.0" }
assert_macros = "2.15.1"
